sudo: required
dist: trusty
os: linux
env:
  - DIST=precise
  - DIST=trusty
cache:
  directories:
  - "$HOME/pbuilder/"
before_cache:
  - rm -rf $HOME/pbuilder/aptcache
script:
  - curl -I https://$PACKAGECLOUD_TOKEN:@packagecloud.io/api/v1/distributions
deploy:
  provider: packagecloud
  repository: dod
  username: heroku
  token:
    secure: r3nXxMPrcuKNoG7dc6lxmKX6IJ8wkZ47d7LxdlT/y2KeT173l5Fq/8Sp+woJ1CC9XU8VFww43SlzWeyUGy0BXAfUPMS8LLdZ+YZssmAQyVNHsmjMCtn4ZS0EMcrStEJNqCvXu3nz+t3HasmMtxfDDzCkVZgBN1QEyj/vql9n+Zs=
  dist: ubuntu/$DIST
  package_glob: "$HOME/result/*.deb"
  on:
    tags: true
notifications:
  email: false
